authors:
    subhajit:
        name: Subhajit Bhar
        description: Freelance Data Scientist
        avatar: img/profile.webp
        url: https://www.subhajitbhar.com
        email: hello@subhajitbhar.com
